[package]
name = "scientific-calculator"
version = "0.1.0"
edition = "2021"

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.20.2"

[dependencies]
ansi_term = "0.12.1"
regex = "1.10.5"
lalrpop-util = { version = "0.20.2", features = ["lexer", "unicode"] }